services:
  db:
    image: postgres:16
    container_name: financial-manager-dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-db
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
      LANG: en_US.utf8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: financial-manager-dev-api
    env_file: .env.dev
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: npm run start:dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - dev-network

volumes:
  pgdata:

networks:
  dev-network:
    driver: bridge
